
directives:
- add_frame:
    name: bin0_origin
    X_PF:
      base_frame: world
      rotation: !Rpy { deg: [0.0, 0.0, 180.0 ]}
      translation: [0.5, 0.05, -0.015]

- add_model:
    name: bin0
    file: package://stacking/planar_bin.sdf

- add_weld:
    parent: bin0_origin
    child: bin0::bin_base

- add_model:
    name: floor
    file: package://stacking/floor.sdf

- add_weld:
    parent: world
    child: floor::box
    X_PC:
        translation: [0, 0, -.5]
